### ISSUE TITLE
询问使用方法

### ISSUE THREAD

**Issue by kousakaharuka9** [raindrop213/AnonTranslator#2]
您好，我已经下载并安装好了相关的插件，请问我下一步应该如何操作？
![9339d6ab47d07643b382020708a13d66](https://github.com/raindrop213/AnonTranslator/assets/172193461/49d5fefe-7e27-4a08-8274-672566960d31)
我的阅读器叫做“伊纪国屋”我应该怎样做才能让它与插件联动？
![e7eb00da06b9335b0c5ca55ec4c88b93](https://github.com/raindrop213/AnonTranslator/assets/172193461/b94966c7-5dec-414f-aa0b-c3350aedb375)
麻烦了

**Comment by raindrop213** [comment]
这是浏览器插件，只能读浏览器中的内容。我的方案是存到Calibre-web，然后才能在浏览器中打开epub，你也可以使用别的应用来在浏览器中打开epub（比如说[https://reader.ttsu.app/manage](https://reader.ttsu.app/manage)），一切的前提是你已经拿到了epub文件，你需要把电子书提取出来）
伊纪我没用过，提取方法就不清楚了，一般都是用bw或者日亚的，比较好提取文件

**Comment by kousakaharuka9** [comment]
> 这是浏览器插件，只能读浏览器中的内容。我的方案是存到Calibre-web，然后才能在浏览器中打开epub，你也可以使用别的应用来在浏览器中打开epub（比如说[https://reader.ttsu.app/manage](https://reader.ttsu.app/manage)），一切的前提是你已经拿到了epub文件，你需要把电子书提取出来）
伊纪我没用过，提取方法就不清楚了，一般都是用bw或者日亚的，比较好提取文件

好的，谢谢
